Week8
AlenoJankowsky/CS50-Harvard pull request #10
Opened 2022-09-22 07:07 UTC by AlenoJankowsky

PR: #10

2022-09-26 07:44 UTC, MKrips requested changes

2022-09-26 07:44 UTC, MKrips commented on week8/homepage/spare-time.html
> +            }
Please put the script in a separate .js-file

2022-09-26 07:44 UTC, MKrips commented on week8/trivia/index.html
> +            // TODO: Add code to check answers to questions
Remove TODO comments if you did that task, otherwise it looks unfinished :)

2022-09-26 07:44 UTC, MKrips commented on week8/trivia/index.html
> +                    rightDecision.style.backgroundColor = 'green';
Please put this in a separate .js-file as well

2022-09-26 07:44 UTC, MKrips commented on week8/homepage/styles.css
> +
Use BEM for ALL classes in ALL files. I can explain if you need :)

2022-09-27 14:18 UTC, DevBastiS requested changes

2022-09-27 14:18 UTC, DevBastiS commented on week8/homepage/resumee.html
> +    <head>
Indent in HTML files should be 2 spaces.
Please adjust this in your vscode and change the files here.

2022-09-27 14:18 UTC, DevBastiS commented on week8/homepage/script.js
> +
```suggestion
```

2022-09-29 06:51 UTC, matthiasdanne approved these changes
Quite good. 👍

2022-09-29 06:51 UTC, matthiasdanne commented on week8/homepage/styles.css
> +.body__eveluate-button {
```suggestion
.body__evaluate-button {
```

2022-10-05 06:31 UTC, DevBastiS approved these changes

2022-10-05 06:32 UTC, merged