Add solution for mario_1_2 #2
AlenoJankowsky/CS50-Harvard pull request #2
Opened 2022-08-04 07:53 UTC by AlenoJankowsky

PR: #2

2022-08-04 09:16 UTC, matthiasdanne requested changes

2022-08-04 09:16 UTC, matthiasdanne commented on mario_1_1.c
> +
```suggestion
```

2022-08-04 09:16 UTC, matthiasdanne commented on mario_1_1.c
> +}
As this red sign indicates, a newline is missing at the end of this file.

2022-08-04 09:16 UTC, matthiasdanne commented on mario_1_2.c
> +}
As this red sign indicates, a newline is missing at the end of this file.

2022-08-04 09:16 UTC, matthiasdanne commented on mario_1_2.c
> +
```suggestion
```

2022-08-04 09:16 UTC, matthiasdanne commented on mario_1_1.c
> +        n = get_int("Height: ");
You should add a hint that indicates valid entries.

```suggestion
        n = get_int("Height: (between 1 and 8)");
```

2022-08-04 09:16 UTC, matthiasdanne commented on mario_1_2.c
> +        n = get_int("Height: ");
See above

2022-08-04 09:16 UTC, matthiasdanne commented on mario_1_2.c
> +
I don't know the coding conventionf for C, but one newline at the end of the for-loop and the main function should be enough.

```suggestion
        }
```

2022-08-04 09:17 UTC, matthiasdanne reviewed
Besides the requested changes, its working as expected. 👍

2022-08-08 06:36 UTC, DevBastiS requested changes

2022-08-08 06:36 UTC, DevBastiS commented on README.md
> +hallöchen popöchen
```suggestion
```

2022-08-08 06:36 UTC, DevBastiS commented on cash.c
> +}
```suggestion
}

```

2022-08-08 06:36 UTC, DevBastiS commented on cash.c
> +    while (cents < 0);
```suggestion
    while (cents < 0);
    
```

Rule of thumb: Always add a blank line before a return statement. Except it is the only statement in a block.

2022-08-08 06:36 UTC, DevBastiS commented on cash.c
> +    n = cents / 25;
```suggestion
    n = cents / 25;
    
```

2022-08-08 06:36 UTC, DevBastiS commented on cash.c
> +}
```suggestion
}

```

2022-08-08 06:36 UTC, DevBastiS commented on cash.c
> +    n = cents / 10;
```suggestion
    n = cents / 10;
    
```

2022-08-08 06:36 UTC, DevBastiS commented on cash.c
> +}
```suggestion
}

```

2022-08-08 06:36 UTC, DevBastiS commented on cash.c
> +}
```suggestion
}

```

2022-08-08 06:36 UTC, DevBastiS commented on cash.c
> +    n = cents / 5;
```suggestion
    n = cents / 5;
    
```

2022-08-08 06:36 UTC, DevBastiS commented on cash.c
> +    n = cents;
```suggestion
    n = cents;
    
```

2022-08-08 06:36 UTC, DevBastiS commented on cash.c
> +    return n;
```suggestion
    return cents;
```

2022-08-08 06:36 UTC, DevBastiS commented on credit.c
> +#include <stdio.h>
```suggestion
#include <stdio.h>

```

2022-08-08 06:36 UTC, DevBastiS commented on credit.c
> +        while (n < 1);
```suggestion
        while (n < 1);
        
```

2022-08-08 06:36 UTC, DevBastiS commented on credit.c
> +        n = n / 10;
```suggestion
        n = n / 10;
        
```

2022-08-08 06:36 UTC, DevBastiS commented on credit.c
> +            productSum = productSum + (n % 10) * 2;
```suggestion
            productSum = productSum + (n % 10) * 2;
            
```

2022-08-08 06:36 UTC, DevBastiS commented on credit.c
> +        if (check % 10 == 0) {
Ok I have like no idea what is happening in this block :D

Please try the following:
Add speaking variables: 
If adding an if statement think about a good name for the condition. (Example: "IsMasterCard") Then move the condition to the variable and use the variable in the if statement (Example: if (IsMasterCard))

Try to lessen the amount of structures needed.
Decrease the amount of ifs, else ifs, whiles and do-whiles.

2022-08-08 06:36 UTC, DevBastiS commented on mario_1_1.c
> +{
Here the braces are in a new line, in the file above they are in the same line as the statement. Please choose one method and stick to it ;)

2022-08-08 06:36 UTC, DevBastiS commented on mario_1_1.c
> +const char WHITE = ' ';
```suggestion
const char WHITE = ' ';

```

2022-08-08 06:36 UTC, DevBastiS commented on mario_1_1.c
> +
```suggestion
```

2022-08-08 06:36 UTC, DevBastiS commented on mario_1_1.c
> +
```suggestion
```

2022-08-08 06:36 UTC, DevBastiS commented on mario_1_2.c
> +const char WHITE = ' ';
```suggestion
const char WHITE = ' ';

```

2022-08-08 06:36 UTC, DevBastiS commented on mario_1_2.c
> +
```suggestion
```

2022-08-08 06:36 UTC, DevBastiS commented on mario_1_2.c
> +
```suggestion
```

2022-08-08 06:36 UTC, DevBastiS commented on mario_1_2.c
> +
```suggestion
```

2022-08-08 06:36 UTC, DevBastiS commented on mario_1_2.c
> +
```suggestion
```

2022-08-08 14:13 UTC, DevBastiS requested changes
Nearly done ;)

2022-08-08 14:13 UTC, DevBastiS commented on cash.c
> +    // Ask how many cents the customer is owed
Remove comments ;)

2022-08-08 14:13 UTC, DevBastiS commented on mario_1_2.c
> +}
```suggestion
}

```

2022-08-08 14:13 UTC, DevBastiS commented on mario_1_1.c
> +}
```suggestion
}

```

2022-08-09 06:12 UTC, DevBastiS approved these changes

2022-08-09 06:12 UTC, DevBastiS commented on cash.c
> +
```suggestion
```

2022-08-09 06:54 UTC, matthiasdanne approved these changes

2022-08-09 07:49 UTC, AlenoJankowsky commented
Thank you for your reviews :)

2022-08-09 07:54 UTC, merged