Week2
AlenoJankowsky/CS50-Harvard pull request #3
Opened 2022-08-08 12:03 UTC by AlenoJankowsky

PR: #3

2022-08-10 13:54 UTC, matthiasdanne requested changes
I've only reviewed scrabble so far.

2022-08-10 13:54 UTC, matthiasdanne commented on scrabble/scrabble.c
> +#include <ctype.h>
Remove comments

2022-08-10 13:54 UTC, matthiasdanne commented on scrabble/scrabble.c
> +    // TODO: Compute and return score for string
So this is still work in progress? Remove this comment, otherwise.

2022-08-10 14:12 UTC, AlenoJankowsky commented on README.md
> +Die Aufgaben für Woche 2 sind hier: https://cs50.harvard.edu/x/2022/psets/2/
In which branch should I add this?

2022-08-10 14:15 UTC, DevBastiS requested changes

2022-08-10 14:15 UTC, DevBastiS commented on caesar/caesar.c
> +
```suggestion
```

2022-08-10 14:15 UTC, DevBastiS commented on caesar/caesar.c
> +    }
```suggestion
    }
    
```

2022-08-10 14:15 UTC, DevBastiS commented on caesar/caesar.c
> +
```suggestion
```

2022-08-10 14:15 UTC, DevBastiS commented on caesar/caesar.c
> +            if(c == 'Z' + 1) {
```suggestion
            if (c == 'Z' + 1) {
```

2022-08-10 14:15 UTC, DevBastiS commented on readability/readability.c
> +
```suggestion
```

2022-08-10 14:15 UTC, DevBastiS commented on readability/readability.c
> +    }
```suggestion
    }
    
```

2022-08-10 14:15 UTC, DevBastiS commented on substitution/substitution.c
> +
```suggestion
```

2022-08-10 14:15 UTC, DevBastiS commented on substitution/substitution.c
> +        printf("ciphertext: ");
```suggestion
        printf("ciphertext: ");
        
```

2022-08-10 14:37 UTC, matthiasdanne requested changes
- Where is the code from week0 and week1?

2022-08-10 14:39 UTC, AlenoJankowsky commented on README.md
> +Die Aufgaben für Woche 2 sind hier: https://cs50.harvard.edu/x/2022/psets/2/
Okay I got it now :D

2022-08-11 06:23 UTC, matthiasdanne commented on scrabble/scrabble.c
> +}
Missing eof

2022-08-11 06:37 UTC, matthiasdanne commented on readability/readability.c
> +        printf("Before Grade 1");
```suggestion
        printf("Before Grade 1\n");
```

2022-08-11 06:37 UTC, matthiasdanne commented on readability/readability.c
> +        printf("Grade 16+");
```suggestion
        printf("Grade 16+\n");
```

2022-08-11 06:37 UTC, matthiasdanne commented on readability/readability.c
> +        printf("Grade %0.f", index);
```suggestion
        printf("Grade %0.f\n", index);
```

2022-08-11 06:42 UTC, matthiasdanne commented on readability/readability.c
> +int count_letters(string s) {
```suggestion
int count_letters(string text) {
```

2022-08-11 06:43 UTC, matthiasdanne commented on readability/readability.c
> +int count_words(string s) {
```suggestion
int count_words(string text) {
```

2022-08-11 06:43 UTC, matthiasdanne commented on readability/readability.c
> +int count_sentences(string s) {
```suggestion
int count_sentences(string text) {
```

2022-08-11 06:45 UTC, matthiasdanne commented on readability/readability.c
> +#include <cs50.h>
Your readability solution is good. 👍

You could improve it further by reducing the amount of times you are iterating over the whole text. Right now you're iterating three times over the whole text, once in each function. You could wrap these functions with the for loop, like this:

```
for (int i = 0; i < strlen(s); i++) {
  string text = ...

  count letters(text, i)
  count words(text, i)
  count sentences(text, i)
}
```

You're passing the current index to each function alongside with the text.

2022-08-11 07:20 UTC, AlenoJankowsky commented on scrabble/scrabble.c
> +}
Do you mean the missing newline in the last row of code?

2022-08-11 08:11 UTC, AlenoJankowsky commented on readability/readability.c
> +#include <cs50.h>
I think that wouldn't work because I have to iterate into a string, in your example "i < strlen(s)" which I firstly input in the for loop. So there ist no string s that exists before the for loop. And if I iterate through the text and do the functions like count_letters etc. they wouldn't exist outside the for loop. And the conditionals have to be outside the for loop because it would print the grade every iteration, and if I return too early in the conditionals, it wouldn't print the correct grade because the string wouldn't have been iterate through. Let me know if I didn't understand your idea because I think you have something in mind I am currently missing...

2022-08-11 08:16 UTC, AlenoJankowsky commented on readability/readability.c
> +#include <cs50.h>
I really think your idea is very good and I am sure I am missing something from your idea but I kind of want to stick to the problem task, because it says it should only take one argument, thus is the text. But I really appreciate your feedback <3

2022-08-11 08:26 UTC, matthiasdanne requested changes

2022-08-11 08:26 UTC, matthiasdanne commented on caesar/caesar.c
> +            if (c == 'z' + 1) {
You should add speaking variables here. `c == 'z' + 1` likely means that the current char is out of bounds.

2022-08-11 08:26 UTC, matthiasdanne commented on caesar/caesar.c
> +    else if (isInUpperAlphabet) {
Duplicate code with just minor differences is always a good hint that something can be refactored. You could store 'A' or 'a' in a variable `a`, and check that in your function. 

So instead change your whole code based on that if-check, you could just change the variables.

2022-08-11 08:59 UTC, matthiasdanne commented on readability/readability.c
> +#include <cs50.h>
This is doable, ask Marc, we implemented this at his solution.

2022-08-11 09:19 UTC, AlenoJankowsky commented on readability/readability.c
> +#include <cs50.h>
Ah okay, thank you

2022-08-11 09:41 UTC, AlenoJankowsky commented on caesar/caesar.c
> +    else if (isInUpperAlphabet) {
I changed something, let me know if you meant that please :)

2022-08-12 06:29 UTC, DevBastiS approved these changes

2022-08-15 08:53 UTC, matthiasdanne requested changes

2022-08-15 08:53 UTC, matthiasdanne commented on substitution/substitution.c
> +        return c;
```suggestion
```

You're returning  `c` at the end of the function anyway.

2022-08-15 08:53 UTC, matthiasdanne commented on substitution/substitution.c
> +    return c;
```suggestion
```

You're returning  `c` at the end of the function anyway.

2022-08-15 08:53 UTC, matthiasdanne commented on substitution/substitution.c
> +    }
The check for `ValidAmountOfArguments` can be part of the `inputIsInvalid` check. If you want to change your error message, you have to change it in two locations right now.

2022-08-15 08:53 UTC, matthiasdanne commented on substitution/substitution.c
> +                if (s[i] == s[j]) {
I think both checks can be combined into one, with a speaking variables.

2022-08-15 11:21 UTC, AlenoJankowsky commented on substitution/substitution.c
> +    }
If I change my code like that, it would print an error message "segmentation fault". I don't know why it occurs, I will check that later.

2022-08-19 12:37 UTC, AlenoJankowsky commented on substitution/substitution.c
> +    }
In meantime, I don't think we are allowed to change that what you are asking, the task says that nothing should be changed besides the functions below. So is it okay for you if I don't change it accordingly?

2022-08-25 09:52 UTC, matthiasdanne requested changes
Just minor improvements, code is good in general.

2022-08-25 09:52 UTC, matthiasdanne commented on week2/substitution/substitution.c
> +    return false;
Can be simplified.

```suggestion
    return strlen(key) == 26
```

2022-08-25 09:52 UTC, matthiasdanne commented on week2/scrabble/scrabble.c
> +return scoreCount;
Fix indent

2022-08-26 12:32 UTC, matthiasdanne approved these changes

2022-08-26 12:34 UTC, merged