Week4
AlenoJankowsky/CS50-Harvard pull request #5
Opened 2022-08-26 14:30 UTC by AlenoJankowsky

PR: #5

2022-09-01 12:51 UTC, DevBastiS requested changes

2022-09-01 12:51 UTC, DevBastiS commented on week4/recover/recover.c
> +
```suggestion
```

2022-09-01 12:51 UTC, DevBastiS commented on week4/filter-less/filter.c
> +    fclose(outptr);
```suggestion
    fclose(outptr);
    
```

2022-09-01 12:51 UTC, DevBastiS commented on week4/filter-more/filter.c
> +
```suggestion
```

2022-09-01 12:51 UTC, DevBastiS commented on week4/filter-more/filter.c
> +
```suggestion
```

2022-09-01 12:51 UTC, DevBastiS commented on week4/filter-more/filter.c
> +
```suggestion
```

2022-09-01 12:51 UTC, DevBastiS commented on week4/filter-more/filter.c
> +
```suggestion
```

2022-09-01 12:51 UTC, DevBastiS commented on week4/recover/recover.c
> +        if(outputImage != NULL) {
```suggestion
        if (outputImage != NULL) {
```

2022-09-01 12:51 UTC, DevBastiS commented on week4/volume/volume.c
> +    }
```suggestion
    }
    
```

2022-09-02 08:40 UTC, DevBastiS requested changes

2022-09-02 08:40 UTC, DevBastiS commented on week4/recover/recover.c
> +        if(outputImage != NULL) {
Still open

2022-09-02 08:40 UTC, DevBastiS commented on week4/recover/recover.c
> +
Still open

2022-09-02 08:40 UTC, DevBastiS commented on week4/volume/volume.c
> +    }
Still open

2022-09-02 08:40 UTC, DevBastiS commented on week4/filter-less/filter.c
> +    fclose(outptr);
Still open.

2022-09-02 12:53 UTC, matthiasdanne requested changes

2022-09-02 12:53 UTC, matthiasdanne commented on week4/filter-less/helpers.c
> +            averageRed =round(sumOfRed / validCounter);
```suggestion
            averageRed = round(sumOfRed / validCounter);
```

2022-09-02 12:53 UTC, matthiasdanne commented on week4/filter-more/helpers.c
> +void edges(int height, int width, RGBTRIPLE image[height][width]) {
This function is hard to read. You should split it into smaller parts.

2022-09-02 14:15 UTC, AlenoJankowsky commented on week4/filter-more/helpers.c
> +void edges(int height, int width, RGBTRIPLE image[height][width]) {
You are so totally right 😂😭

2022-09-07 07:56 UTC, MKrips requested changes

2022-09-07 07:56 UTC, MKrips commented on week4/filter-less/helpers.c
> +                bool isActuallyOriginalValue = heightIterator == blurHeight && widthIterator == blurWidth;
You should check first if the pixel is valid and then get its rgb values if it is.

2022-09-07 07:56 UTC, MKrips commented on week4/filter-less/helpers.c
> +            float validCounter = 1.0;
Is there a reason for this to be a float?

2022-09-07 07:56 UTC, MKrips commented on week4/filter-less/helpers.c
> +            while (!allSumsAreComputed) {
You could make two for-loop out of this. That would simplify the later half of this loop.

2022-09-08 06:06 UTC, AlenoJankowsky commented on week4/filter-less/helpers.c
> +            while (!allSumsAreComputed) {
I don't know why I always end up creating custom loops to imitate actual for loops, sometimes it just confuses me because it is actually easy to create these for loops. I could have saved extra time there 😄

2022-09-08 13:47 UTC, MKrips requested changes

2022-09-08 13:47 UTC, MKrips commented on week4/filter-less/helpers.c
> +                    }
```suggestion
                    bool adjacentPixelIsValid = (blurHeight + heightIterator) >= 0 && (blurHeight + heightIterator) < height && (blurWidth + widthIterator) >= 0 && (blurWidth + widthIterator) < width;
                    if (!adjacentPixelIsValid) {
                        continue;
                    }
                    
                    bool isActuallyOriginalValue = heightIterator == blurHeight && widthIterator == blurWidth;

                    currentBlurBlueValue = image[blurHeight + heightIterator][blurWidth + widthIterator].rgbtBlue;
                    currentBlurGreenValue = image[blurHeight + heightIterator][blurWidth + widthIterator].rgbtGreen;
                    currentBlurRedValue = image[blurHeight + heightIterator][blurWidth + widthIterator].rgbtRed;
```
An early exit is more readable and performant for these kind of conditions.

2022-09-08 13:47 UTC, MKrips commented on week4/filter-more/helpers.c
> +                        currentEdgeBlueValue = copy[edgeHeight + heightIterator][edgeWidth + widthIterator].rgbtBlue;
This would be another situation for an early exit.

2022-09-09 06:01 UTC, DevBastiS commented on week4/filter-less/filter.c
> +    fclose(outptr);
Still not done

2022-09-09 06:01 UTC, DevBastiS commented on week4/volume/volume.c
> +    }
Still not done

2022-09-09 10:48 UTC, DevBastiS approved these changes

2022-09-12 11:58 UTC, MKrips approved these changes

2022-09-12 12:32 UTC, merged