Week5
AlenoJankowsky/CS50-Harvard pull request #7
Opened 2022-09-05 13:35 UTC by AlenoJankowsky

PR: #7

2022-09-06 14:03 UTC, DevBastiS requested changes

2022-09-06 14:03 UTC, DevBastiS commented on week5/inheritance/inheritance.c
> +    }
Can you solve this with a switch case?

2022-09-08 07:48 UTC, AlenoJankowsky commented on week5/inheritance/inheritance.c
> +    }
We were not allowed to change this block of code because it was not included in our TODOs but I surely can implement this if you want :)

2022-09-09 06:02 UTC, DevBastiS approved these changes

2022-09-09 06:02 UTC, DevBastiS commented on week5/inheritance/inheritance.c
> +
```suggestion
```

2022-09-09 06:02 UTC, DevBastiS commented on week5/inheritance/inheritance.c
> +
```suggestion
```

2022-09-09 06:30 UTC, MKrips approved these changes

2022-09-12 11:04 UTC, merged