Week7
AlenoJankowsky/CS50-Harvard pull request #9
Opened 2022-09-15 09:33 UTC by AlenoJankowsky

PR: #9

2022-09-16 06:17 UTC, DevBastiS requested changes

2022-09-16 06:17 UTC, DevBastiS commented on week7/movies/1.sql
> +SELECT title FROM movies WHERE year == 2008;
Missing EOF in many files.

2022-09-16 06:17 UTC, DevBastiS commented on week7/movies/11.sql
> +ORDER BY ratings.rating DESC LIMIT 5;
Would be easier to read if you format your queries like this:
```suggestion
SELECT title FROM movies
LEFT JOIN ratings ON movies.id = ratings.movie_id 
LEFT JOIN stars ON movies.id = stars.movie_id
LEFT JOIN people ON stars.person_id = people.id 
WHERE people.name == "Chadwick Boseman"
ORDER BY ratings.rating DESC
LIMIT 5;
```

2022-09-19 05:39 UTC, DevBastiS approved these changes

2022-09-23 08:03 UTC, MKrips approved these changes

2022-09-23 08:28 UTC, merged